spring:
     social:
        facebook:
            app-id:176844726880868
            app-secret:1f089a2699c8b8ad261ab9730f9c0626
server:
    port:8080
    ssl:
      key-store:/Users/ppatrot/Downloads/facebookLogin/src/main/resources/baeldung.p12
      key-store-password:Andy/4452
      keyStoreType:PKCS12
      keyAlias:baeldung
